kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: fedora-server-small-custom
  namespace: openshift
  labels:
    os.template.kubevirt.io/fedora35: 'true'
    app.kubernetes.io/part-of: hyperconverged-cluster
    os.template.kubevirt.io/fedora36: 'true'
    flavor.template.kubevirt.io/small: 'true'
    template.kubevirt.io/version: v0.24.2
    app.kubernetes.io/version: 4.12.3
    template.kubevirt.io/type: base
    app.kubernetes.io/component: templating
    template.kubevirt.io/default-os-variant: 'true'
    app.kubernetes.io/name: common-templates
    workload.template.kubevirt.io/server: 'true'
  annotations:
    template.kubevirt.io/provider: Red Hat
    template.kubevirt.io/provider-url: 'https://www.fedoraproject.org'
    name.os.template.kubevirt.io/fedora35: Fedora 35 or higher
    name.os.template.kubevirt.io/fedora36: Fedora 35 or higher
    template.kubevirt.io/containerdisks: |
      quay.io/containerdisks/fedora:latest
      quay.io/containerdisks/fedora:35
      quay.io/containerdisks/fedora:36
    template.kubevirt.io/version: v1alpha1
    openshift.io/display-name: Fedora VM
    openshift.io/documentation-url: 'https://github.com/kubevirt/common-templates'
    template.kubevirt.io/images: >
      https://dl.fedoraproject.org/pub/fedora/linux/releases/35/Cloud/x86_64/images/Fedora-Cloud-Base-35-1.2.x86_64.qcow2

      https://dl.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2
    operator-sdk/primary-resource-type: SSP.ssp.kubevirt.io
    defaults.template.kubevirt.io/disk: rootdisk
    template.kubevirt.io/editable: |
      /objects[0].spec.template.spec.domain.cpu.sockets
      /objects[0].spec.template.spec.domain.cpu.cores
      /objects[0].spec.template.spec.domain.cpu.threads
      /objects[0].spec.template.spec.domain.resources.requests.memory
      /objects[0].spec.template.spec.domain.devices.disks
      /objects[0].spec.template.spec.volumes
      /objects[0].spec.template.spec.networks
    template.openshift.io/bindable: 'false'
    operator-sdk/primary-resource: openshift-cnv/ssp-kubevirt-hyperconverged
    tags: 'hidden,kubevirt,virtualmachine,fedora'
    template.kubevirt.io/provider-support-level: Community
    description: >-
      Template for Fedora 35 VM or newer. A PVC with the Fedora disk image must
      be available.
    openshift.io/support-url: 'https://github.com/kubevirt/common-templates/issues'
    iconClass: icon-fedora
    openshift.io/provider-display-name: Red Hat
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: template.openshift.io/v1
      time: '2023-06-16T11:58:29Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:template.kubevirt.io/editable': {}
            'f:operator-sdk/primary-resource': {}
            'f:operator-sdk/primary-resource-type': {}
            'f:defaults.template.kubevirt.io/disk': {}
            'f:template.kubevirt.io/provider-support-level': {}
            'f:description': {}
            'f:template.openshift.io/bindable': {}
            'f:iconClass': {}
            'f:tags': {}
            .: {}
            'f:template.kubevirt.io/provider': {}
            'f:template.kubevirt.io/provider-url': {}
            'f:name.os.template.kubevirt.io/fedora35': {}
            'f:template.kubevirt.io/containerdisks': {}
            'f:name.os.template.kubevirt.io/fedora36': {}
            'f:openshift.io/support-url': {}
            'f:openshift.io/provider-display-name': {}
            'f:template.kubevirt.io/images': {}
            'f:openshift.io/display-name': {}
            'f:template.kubevirt.io/version': {}
            'f:openshift.io/documentation-url': {}
          'f:labels':
            'f:template.kubevirt.io/default-os-variant': {}
            'f:app.kubernetes.io/name': {}
            .: {}
            'f:app.kubernetes.io/part-of': {}
            'f:workload.template.kubevirt.io/server': {}
            'f:flavor.template.kubevirt.io/small': {}
            'f:os.template.kubevirt.io/fedora35': {}
            'f:app.kubernetes.io/version': {}
            'f:os.template.kubevirt.io/fedora36': {}
            'f:template.kubevirt.io/type': {}
            'f:template.kubevirt.io/version': {}
            'f:app.kubernetes.io/component': {}
    - manager: Mozilla
      operation: Update
      apiVersion: template.openshift.io/v1
      time: '2023-06-16T14:18:57Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:objects': {}
        'f:parameters': {}
objects:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      annotations:
        vm.kubevirt.io/validations: |
          [
            {
              "name": "minimal-required-memory",
              "path": "jsonpath::.spec.domain.resources.requests.memory",
              "rule": "integer",
              "message": "This VM requires more memory.",
              "min": 1073741824
            }
          ]
      labels:
        app: '${NAME}'
        vm.kubevirt.io/template: fedora-server-small-custom
        vm.kubevirt.io/template.revision: '1'
        vm.kubevirt.io/template.version: v0.24.2
      name: '${NAME}'
    spec:
      dataVolumeTemplates:
        - apiVersion: cdi.kubevirt.io/v1beta1
          kind: DataVolume
          metadata:
            name: '${NAME}'
          spec:
            sourceRef:
              kind: DataSource
              name: '${DATA_SOURCE_NAME}'
              namespace: '${DATA_SOURCE_NAMESPACE}'
            storage:
              resources:
                requests:
                  storage: 30Gi
      running: false
      template:
        metadata:
          annotations:
            vm.kubevirt.io/flavor: small
            vm.kubevirt.io/os: fedora
            vm.kubevirt.io/workload: server
          labels:
            kubevirt.io/domain: '${NAME}'
            kubevirt.io/size: small
        spec:
          accessCredentials:
            - sshPublicKey:
                propagationMethod:
                  configDrive: {}
                source:
                  secret:
                    secretName: '${SSH_PUBLIC_KEY}'
          domain:
            cpu:
              cores: 1
              sockets: 1
              threads: 1
            devices:
              disks:
                - disk:
                    bus: virtio
                  name: rootdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
              interfaces:
                - masquerade: {}
                  model: virtio
                  name: default
              networkInterfaceMultiqueue: true
              rng: {}
            features:
              smm:
                enabled: true
            firmware:
              bootloader:
                efi: {}
            machine:
              type: pc-q35-rhel8.6.0
            resources:
              requests:
                memory: 2Gi
          evictionStrategy: LiveMigrate
          networks:
            - name: default
              pod: {}
          terminationGracePeriodSeconds: 180
          volumes:
            - dataVolume:
                name: '${NAME}'
              name: rootdisk
            - cloudInitConfigDrive:
                userData: |-
                  #cloud-config
                  user: fedora
                  password: ${CLOUD_USER_PASSWORD}
                  chpasswd: { expire: False }
                  packages:
                     - git
                  write_files:
                     - path: /etc/ssh/sshd_config.d/01-custom.conf
                       owner: root:root
                       content: PasswordAuthentication yes
                       permissions: '0644'
                     - path: /var/www/html/index.html
                       owner: root:root
                       content: hello world!
                       permissions: '0644'
              name: cloudinitdisk
parameters:
  - name: NAME
    description: VM name
    generate: expression
    from: 'fedora-[a-z0-9]{16}'
  - name: DATA_SOURCE_NAME
    description: Name of the DataSource to clone
    value: fedora
  - name: DATA_SOURCE_NAMESPACE
    description: Namespace of the DataSource
    value: openshift-virtualization-os-images
  - name: CLOUD_USER_PASSWORD
    description: default password
    value: redhat
  - name: SSH_PUBLIC_KEY
    description: the public key secret for ssh
    required: true
